package dollynho;

import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vinimaz
 */
public class jFrameDollynhoClient extends javax.swing.JFrame {
    InterfaceServ refServidor;
    ControllerClient controller;
    /**
     * Creates new form jFrameDollynhoClient
     * @throws java.rmi.RemoteException
     * @throws java.rmi.NotBoundException
     */
    public jFrameDollynhoClient() throws RemoteException, NotBoundException, ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        String laf = UIManager.getSystemLookAndFeelClassName();
        UIManager.setLookAndFeel(laf);
        initComponents();
        controller = new ControllerClient(this);
        System.out.println("Rodando cliente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mainPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuscaPassagem = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textPasOrigem = new javax.swing.JTextField();
        textPasDestino = new javax.swing.JTextField();
        textPasData = new javax.swing.JTextField();
        textPasAdultos = new javax.swing.JTextField();
        textPasCriancas = new javax.swing.JTextField();
        btPasBuscar = new javax.swing.JButton();
        btPasAviseme = new javax.swing.JButton();
        textPasDataVolta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btPasMostraTudo = new javax.swing.JButton();
        btComprarPas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        textHospHotel = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textHospCidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textHospDataEntrada = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textHospDataSaida = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBuscaHospedagem = new javax.swing.JTable();
        btHospAviseme = new javax.swing.JButton();
        btHospBuscar = new javax.swing.JButton();
        btHospMostraTudo = new javax.swing.JButton();
        btComprarHosp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        paneCompraPas = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btCompraConfirmaPas = new javax.swing.JButton();
        btCompraCancelaPas = new javax.swing.JButton();
        textCompraNomePas = new javax.swing.JTextField();
        textCompraNumCartaoPas = new javax.swing.JTextField();
        textCompraDescricaoPas = new javax.swing.JLabel();
        paneCompraHosp = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btCompraConfirmaHosp = new javax.swing.JButton();
        btCompraCancelaHosp = new javax.swing.JButton();
        textCompraNomeHosp = new javax.swing.JTextField();
        textCompraNumCartaoHosp = new javax.swing.JTextField();
        textCompraDescricaoHosp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dollynho Airlines");

        jLabel1.setIcon(new javax.swing.ImageIcon("/Volumes/HD750GBMAC/vinimaz/Dropbox/Facu/2016.1/SD/Netbeans Dollynho/DollynhoAirlines/src/dollynhoIntro100x119.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 51));
        jLabel2.setText("Dollynho Airlines");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("A agência amiguinha");

        tableBuscaPassagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableBuscaPassagem);

        jLabel5.setText("Origem");

        jLabel6.setText("Destino");

        jLabel7.setText("Data");

        jLabel8.setText("Adultos");

        jLabel9.setText("Crianças");

        textPasData.setText("DD/MM/AAAA");

        textPasAdultos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPasAdultosActionPerformed(evt);
            }
        });

        btPasBuscar.setText("Buscar");
        btPasBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPasBuscarActionPerformed(evt);
            }
        });

        btPasAviseme.setText("AVISE-ME");
        btPasAviseme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPasAvisemeActionPerformed(evt);
            }
        });

        textPasDataVolta.setText("DD/MM/AAAA");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("*volta opcional");

        btPasMostraTudo.setText("Mostrar tudo");
        btPasMostraTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPasMostraTudoActionPerformed(evt);
            }
        });

        btComprarPas.setText("Comprar");
        btComprarPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprarPasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textPasCriancas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btPasAviseme)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btPasBuscar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textPasOrigem)
                                    .addComponent(textPasAdultos)
                                    .addComponent(textPasDestino)
                                    .addComponent(textPasData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(btPasMostraTudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(textPasDataVolta, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel14))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btComprarPas)))
                                        .addGap(13, 13, 13)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textPasOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btComprarPas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textPasDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textPasData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPasDataVolta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textPasAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPasMostraTudo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textPasCriancas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPasBuscar)
                    .addComponent(btPasAviseme))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPane.addTab("Buscar Passagens", jPanel1);

        jLabel10.setText("Hotel");

        jLabel11.setText("Cidade");

        jLabel12.setText("Data Entrada");

        textHospDataEntrada.setText("DD/MM/AAAA");
        textHospDataEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHospDataEntradaActionPerformed(evt);
            }
        });

        jLabel13.setText("Data Saida");

        textHospDataSaida.setText("DD/MM/AAAA");
        textHospDataSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHospDataSaidaActionPerformed(evt);
            }
        });

        tableBuscaHospedagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableBuscaHospedagem);

        btHospAviseme.setText("AVISE-ME");
        btHospAviseme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHospAvisemeActionPerformed(evt);
            }
        });

        btHospBuscar.setText("Buscar");
        btHospBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHospBuscarActionPerformed(evt);
            }
        });

        btHospMostraTudo.setText("Mostrar tudo");
        btHospMostraTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHospMostraTudoActionPerformed(evt);
            }
        });

        btComprarHosp.setText("Comprar");
        btComprarHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprarHospActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textHospHotel, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(textHospDataEntrada, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textHospDataSaida)
                            .addComponent(textHospCidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btHospMostraTudo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btHospAviseme)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btHospBuscar))
                            .addComponent(btComprarHosp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textHospHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textHospCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(textHospDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHospMostraTudo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(textHospDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHospAviseme)
                    .addComponent(btHospBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btComprarHosp)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPane.addTab("Buscar Hospedagem", jPanel2);

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Para cadastrar um aviso de baixa de preço selecione o item e clique em AVISE-ME");

        jLabel15.setText("Você está comprando");

        jLabel16.setText("Nome");

        jLabel17.setText("Número do Cartão");

        btCompraConfirmaPas.setText("Confirma compra");
        btCompraConfirmaPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCompraConfirmaPasActionPerformed(evt);
            }
        });

        btCompraCancelaPas.setText("Cancela compra");
        btCompraCancelaPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCompraCancelaPasActionPerformed(evt);
            }
        });

        textCompraDescricaoPas.setText("*****************");

        javax.swing.GroupLayout paneCompraPasLayout = new javax.swing.GroupLayout(paneCompraPas);
        paneCompraPas.setLayout(paneCompraPasLayout);
        paneCompraPasLayout.setHorizontalGroup(
            paneCompraPasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCompraPasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(paneCompraPasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15))
                .addGap(25, 25, 25)
                .addGroup(paneCompraPasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneCompraPasLayout.createSequentialGroup()
                        .addGroup(paneCompraPasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCompraNomePas)
                            .addComponent(textCompraNumCartaoPas))
                        .addGap(116, 116, 116))
                    .addGroup(paneCompraPasLayout.createSequentialGroup()
                        .addComponent(textCompraDescricaoPas)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCompraPasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCompraCancelaPas)
                .addGap(18, 18, 18)
                .addComponent(btCompraConfirmaPas)
                .addGap(16, 16, 16))
        );
        paneCompraPasLayout.setVerticalGroup(
            paneCompraPasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCompraPasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(paneCompraPasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(textCompraDescricaoPas))
                .addGap(18, 18, 18)
                .addGroup(paneCompraPasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(textCompraNomePas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneCompraPasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(textCompraNumCartaoPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(paneCompraPasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCompraConfirmaPas)
                    .addComponent(btCompraCancelaPas))
                .addGap(22, 22, 22))
        );

        jLabel18.setText("Você está comprando");

        jLabel19.setText("Nome");

        jLabel20.setText("Número do Cartão");

        btCompraConfirmaHosp.setText("Confirma compra");
        btCompraConfirmaHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCompraConfirmaHospActionPerformed(evt);
            }
        });

        btCompraCancelaHosp.setText("Cancela compra");
        btCompraCancelaHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCompraCancelaHospActionPerformed(evt);
            }
        });

        textCompraDescricaoHosp.setText("*****************");

        javax.swing.GroupLayout paneCompraHospLayout = new javax.swing.GroupLayout(paneCompraHosp);
        paneCompraHosp.setLayout(paneCompraHospLayout);
        paneCompraHospLayout.setHorizontalGroup(
            paneCompraHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCompraHospLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(paneCompraHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18))
                .addGap(25, 25, 25)
                .addGroup(paneCompraHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneCompraHospLayout.createSequentialGroup()
                        .addGroup(paneCompraHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCompraNomeHosp)
                            .addComponent(textCompraNumCartaoHosp))
                        .addGap(116, 116, 116))
                    .addGroup(paneCompraHospLayout.createSequentialGroup()
                        .addComponent(textCompraDescricaoHosp)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCompraHospLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCompraCancelaHosp)
                .addGap(18, 18, 18)
                .addComponent(btCompraConfirmaHosp)
                .addGap(16, 16, 16))
        );
        paneCompraHospLayout.setVerticalGroup(
            paneCompraHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCompraHospLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(paneCompraHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(textCompraDescricaoHosp))
                .addGap(18, 18, 18)
                .addGroup(paneCompraHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(textCompraNomeHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneCompraHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(textCompraNumCartaoHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(paneCompraHospLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCompraConfirmaHosp)
                    .addComponent(btCompraCancelaHosp))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paneCompraPas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(paneCompraHosp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneCompraPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneCompraHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPasAdultosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPasAdultosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPasAdultosActionPerformed

    private void textHospDataSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHospDataSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHospDataSaidaActionPerformed

    private void textHospDataEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHospDataEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHospDataEntradaActionPerformed

    private void btPasMostraTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPasMostraTudoActionPerformed
        try {
            // TODO add your handling code here:
            controller.mostraTudoPassagem();
        } catch (RemoteException ex) {
            Logger.getLogger(jFrameDollynhoClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btPasMostraTudoActionPerformed

    private void btHospMostraTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHospMostraTudoActionPerformed
        try {
            // TODO add your handling code here:
            controller.mostraTudoHospedagem();
        } catch (RemoteException ex) {
            Logger.getLogger(jFrameDollynhoClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btHospMostraTudoActionPerformed

    private void btPasAvisemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPasAvisemeActionPerformed
        try {
            // TODO add your handling code here:
            controller.avisemePassagem();
        } catch (RemoteException ex) {
            Logger.getLogger(jFrameDollynhoClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btPasAvisemeActionPerformed

    private void btHospAvisemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHospAvisemeActionPerformed
        try {
            // TODO add your handling code here:
            controller.avisemeHospedagem();
        } catch (RemoteException ex) {
            Logger.getLogger(jFrameDollynhoClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btHospAvisemeActionPerformed

    private void btHospBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHospBuscarActionPerformed
        try {
            // TODO add your handling code here:
            controller.buscaHospedagem();
        } catch (RemoteException ex) {
            Logger.getLogger(jFrameDollynhoClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btHospBuscarActionPerformed

    private void btPasBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPasBuscarActionPerformed
        try {
            // TODO add your handling code here:
            controller.buscaPassagem();
        } catch (RemoteException ex) {
            Logger.getLogger(jFrameDollynhoClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btPasBuscarActionPerformed

    private void btCompraConfirmaPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCompraConfirmaPasActionPerformed
        try {
            // TODO add your handling code here:
            controller.compraPassagem();
        } catch (RemoteException ex) {
            Logger.getLogger(jFrameDollynhoClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btCompraConfirmaPasActionPerformed

    private void btCompraConfirmaHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCompraConfirmaHospActionPerformed
        try {
            // TODO add your handling code here:
            controller.compraHospedagem();
        } catch (RemoteException ex) {
            Logger.getLogger(jFrameDollynhoClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btCompraConfirmaHospActionPerformed

    private void btComprarPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprarPasActionPerformed
        // TODO add your handling code here:
        controller.abreCompraPassagem();
    }//GEN-LAST:event_btComprarPasActionPerformed

    private void btComprarHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprarHospActionPerformed
        // TODO add your handling code here:
        controller.abreCompraHospedagem();
    }//GEN-LAST:event_btComprarHospActionPerformed

    private void btCompraCancelaHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCompraCancelaHospActionPerformed
        // TODO add your handling code here:
        controller.fechaPaneCompraHospedagem();
    }//GEN-LAST:event_btCompraCancelaHospActionPerformed

    private void btCompraCancelaPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCompraCancelaPasActionPerformed
        // TODO add your handling code here:
        controller.fechaPaneCompraPassagem();
    }//GEN-LAST:event_btCompraCancelaPasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameDollynhoClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameDollynhoClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameDollynhoClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameDollynhoClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new jFrameDollynhoClient().setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(jFrameDollynhoClient.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NotBoundException ex) {
                    Logger.getLogger(jFrameDollynhoClient.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(jFrameDollynhoClient.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(jFrameDollynhoClient.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(jFrameDollynhoClient.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(jFrameDollynhoClient.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public JTable getTableBuscaHospedagem() {
        return tableBuscaHospedagem;
    }

    public JTable getTableBuscaPassagem() {
        return tableBuscaPassagem;
    }

    public JTextField getTextHospCidade() {
        return textHospCidade;
    }

    public JTextField getTextHospDataEntrada() {
        return textHospDataEntrada;
    }

    public JTextField getTextHospDataSaida() {
        return textHospDataSaida;
    }

    public JTextField getTextHospHotel() {
        return textHospHotel;
    }

    public JTextField getTextPasAdultos() {
        return textPasAdultos;
    }

    public JTextField getTextPasCriancas() {
        return textPasCriancas;
    }

    public JTextField getTextPasData() {
        return textPasData;
    }

    public JTextField getTextPasDestino() {
        return textPasDestino;
    }

    public JTextField getTextPasOrigem() {
        return textPasOrigem;
    }

    public JTextField getTextPasDataVolta() {
        return textPasDataVolta;
    }

    public JPanel getPaneCompraHosp() {
        return paneCompraHosp;
    }

    public JPanel getPaneCompraPas() {
        return paneCompraPas;
    }

    public JLabel getTextCompraDescricaoHosp() {
        return textCompraDescricaoHosp;
    }

    public JLabel getTextCompraDescricaoPas() {
        return textCompraDescricaoPas;
    }

    public JTextField getTextCompraNomeHosp() {
        return textCompraNomeHosp;
    }

    public JTextField getTextCompraNomePas() {
        return textCompraNomePas;
    }

    public JTextField getTextCompraNumCartaoHosp() {
        return textCompraNumCartaoHosp;
    }

    public JTextField getTextCompraNumCartaoPas() {
        return textCompraNumCartaoPas;
    }

    public JTabbedPane getMainPane() {
        return mainPane;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCompraCancelaHosp;
    private javax.swing.JButton btCompraCancelaPas;
    private javax.swing.JButton btCompraConfirmaHosp;
    private javax.swing.JButton btCompraConfirmaPas;
    private javax.swing.JButton btComprarHosp;
    private javax.swing.JButton btComprarPas;
    private javax.swing.JButton btHospAviseme;
    private javax.swing.JButton btHospBuscar;
    private javax.swing.JButton btHospMostraTudo;
    private javax.swing.JButton btPasAviseme;
    private javax.swing.JButton btPasBuscar;
    private javax.swing.JButton btPasMostraTudo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane mainPane;
    private javax.swing.JPanel paneCompraHosp;
    private javax.swing.JPanel paneCompraPas;
    private javax.swing.JTable tableBuscaHospedagem;
    private javax.swing.JTable tableBuscaPassagem;
    private javax.swing.JLabel textCompraDescricaoHosp;
    private javax.swing.JLabel textCompraDescricaoPas;
    private javax.swing.JTextField textCompraNomeHosp;
    private javax.swing.JTextField textCompraNomePas;
    private javax.swing.JTextField textCompraNumCartaoHosp;
    private javax.swing.JTextField textCompraNumCartaoPas;
    private javax.swing.JTextField textHospCidade;
    private javax.swing.JTextField textHospDataEntrada;
    private javax.swing.JTextField textHospDataSaida;
    private javax.swing.JTextField textHospHotel;
    private javax.swing.JTextField textPasAdultos;
    private javax.swing.JTextField textPasCriancas;
    private javax.swing.JTextField textPasData;
    private javax.swing.JTextField textPasDataVolta;
    private javax.swing.JTextField textPasDestino;
    private javax.swing.JTextField textPasOrigem;
    // End of variables declaration//GEN-END:variables
}
