/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dollynho;

import java.rmi.AlreadyBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author vinimaz
 */
public class dollynhoAirlinesJFrame extends javax.swing.JFrame {
    ControllerServer controller;
    ServImpl server;
    
    /**
     * Creates new form dollynhoAirlinesJFrame
     */
    public dollynhoAirlinesJFrame() throws RemoteException, AlreadyBoundException, ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        String laf = UIManager.getSystemLookAndFeelClassName();
        UIManager.setLookAndFeel(laf);
        initComponents();
        
        // Cria o controller que implementa um "Modelo MVC" para atualizar a interface
        controller      = new ControllerServer(this);
        server          = new ServImpl(controller);
        int port = 6789;
        //Cria o servidor de nomes
        Registry referenciaServicoNomes = LocateRegistry.createRegistry(port);
        referenciaServicoNomes.bind("Dollynho", server);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     * NOTA: Os event Handlers da UI (interface gráfica) utilizam métodos do controller,
     * adotando uma forma de modelo MVC (model-view-controller). Nesse caso, essa classe
     * (view) utiliza métodos do controller para modificar o modelo.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        introPane = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaPassagens = new javax.swing.JTable();
        btAddPas = new javax.swing.JButton();
        editPas = new javax.swing.JButton();
        btRemovePas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaHospedagem = new javax.swing.JTable();
        btAddHosp = new javax.swing.JButton();
        btEditHosp = new javax.swing.JButton();
        btRemoveHosp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaNotificacoes = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        paneCadastroHospedagem = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldHospHotel = new javax.swing.JTextField();
        fieldHospCidade = new javax.swing.JTextField();
        fieldHospPreco = new javax.swing.JTextField();
        fieldHospQuantidade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        paneCadastroPassagem = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fieldPasData = new javax.swing.JTextField();
        fieldPasOrigem = new javax.swing.JTextField();
        fieldPasDestino = new javax.swing.JTextField();
        fieldPasPreco = new javax.swing.JTextField();
        fieldPasQuantidade = new javax.swing.JTextField();
        btCancelPas = new javax.swing.JButton();
        btSalvarPassagem = new javax.swing.JButton();
        paneCadastroPassagemEdit = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        fieldPasDataEdit = new javax.swing.JTextField();
        fieldPasOrigemEdit = new javax.swing.JTextField();
        fieldPasDestinoEdit = new javax.swing.JTextField();
        fieldPasPrecoEdit = new javax.swing.JTextField();
        fieldPasQuantidadeEdit = new javax.swing.JTextField();
        btCancelEditPas = new javax.swing.JButton();
        btSalvarEditPassagem = new javax.swing.JButton();
        paneCadastroHospedagemEdit = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        fieldHospHotelEdit = new javax.swing.JTextField();
        fieldHospCidadeEdit = new javax.swing.JTextField();
        fieldHospPrecoEdit = new javax.swing.JTextField();
        fieldHospQuantidadeEdit = new javax.swing.JTextField();
        btHospCancelaEdit = new javax.swing.JButton();
        btHospSalvaEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server Dollynho Airlines");
        setPreferredSize(new java.awt.Dimension(640, 480));

        introPane.setToolTipText("");
        introPane.setPreferredSize(new java.awt.Dimension(640, 480));

        tabelaPassagens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelaPassagens);

        btAddPas.setText("Adicionar");
        btAddPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddPasActionPerformed(evt);
            }
        });

        editPas.setText("Editar");
        editPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPasActionPerformed(evt);
            }
        });

        btRemovePas.setBackground(new java.awt.Color(255, 51, 51));
        btRemovePas.setForeground(new java.awt.Color(255, 51, 0));
        btRemovePas.setText("Apagar");
        btRemovePas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemovePasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btAddPas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editPas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemovePas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddPas)
                    .addComponent(editPas)
                    .addComponent(btRemovePas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Passagem", jPanel1);

        tabelaHospedagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaHospedagem);

        btAddHosp.setText("Adicionar");
        btAddHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddHospActionPerformed(evt);
            }
        });

        btEditHosp.setText("Editar");
        btEditHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditHospActionPerformed(evt);
            }
        });

        btRemoveHosp.setForeground(new java.awt.Color(255, 51, 51));
        btRemoveHosp.setText("Apagar");
        btRemoveHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveHospActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btAddHosp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEditHosp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRemoveHosp)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddHosp)
                    .addComponent(btEditHosp)
                    .addComponent(btRemoveHosp))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Hospedagem", jPanel2);

        tabelaNotificacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelaNotificacoes);

        jLabel6.setText("Pedidos de aviso cadastrados pelos usuários");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Notificações Cadastradas", jPanel3);

        javax.swing.GroupLayout introPaneLayout = new javax.swing.GroupLayout(introPane);
        introPane.setLayout(introPaneLayout);
        introPaneLayout.setHorizontalGroup(
            introPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        introPaneLayout.setVerticalGroup(
            introPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Cadastro de Hospedagem");

        jLabel2.setText("Hotel");

        jLabel3.setText("Cidade");

        jLabel4.setText("Preço");

        jLabel5.setText("Quantidade");

        fieldHospHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHospHotelActionPerformed(evt);
            }
        });

        fieldHospCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHospCidadeActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salvar");

        javax.swing.GroupLayout paneCadastroHospedagemLayout = new javax.swing.GroupLayout(paneCadastroHospedagem);
        paneCadastroHospedagem.setLayout(paneCadastroHospedagemLayout);
        paneCadastroHospedagemLayout.setHorizontalGroup(
            paneCadastroHospedagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCadastroHospedagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paneCadastroHospedagemLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(paneCadastroHospedagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneCadastroHospedagemLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(220, 220, 220))
                    .addGroup(paneCadastroHospedagemLayout.createSequentialGroup()
                        .addGroup(paneCadastroHospedagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paneCadastroHospedagemLayout.createSequentialGroup()
                                .addGroup(paneCadastroHospedagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(paneCadastroHospedagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldHospCidade, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fieldHospPreco, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fieldHospQuantidade)
                                    .addComponent(fieldHospHotel, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)))
                            .addGroup(paneCadastroHospedagemLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        paneCadastroHospedagemLayout.setVerticalGroup(
            paneCadastroHospedagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCadastroHospedagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneCadastroHospedagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldHospHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneCadastroHospedagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldHospCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneCadastroHospedagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldHospPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneCadastroHospedagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldHospQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(paneCadastroHospedagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Cadastro de Passagem");

        jLabel8.setText("Data");

        jLabel9.setText("Origem");

        jLabel10.setText("Destino");

        jLabel11.setText("Preço");

        jLabel12.setText("Quantidade");

        fieldPasData.setText("DD/MM/YYYY");
        fieldPasData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPasDataActionPerformed(evt);
            }
        });

        fieldPasOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPasOrigemActionPerformed(evt);
            }
        });

        btCancelPas.setText("Cancelar");
        btCancelPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelPasActionPerformed(evt);
            }
        });

        btSalvarPassagem.setText("Salvar");
        btSalvarPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarPassagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneCadastroPassagemLayout = new javax.swing.GroupLayout(paneCadastroPassagem);
        paneCadastroPassagem.setLayout(paneCadastroPassagemLayout);
        paneCadastroPassagemLayout.setHorizontalGroup(
            paneCadastroPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCadastroPassagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(paneCadastroPassagemLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(paneCadastroPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneCadastroPassagemLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(220, 220, 220))
                    .addGroup(paneCadastroPassagemLayout.createSequentialGroup()
                        .addGroup(paneCadastroPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paneCadastroPassagemLayout.createSequentialGroup()
                                .addGroup(paneCadastroPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(paneCadastroPassagemLayout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneCadastroPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldPasOrigem)
                                    .addComponent(fieldPasDestino)
                                    .addComponent(fieldPasQuantidade)
                                    .addComponent(fieldPasPreco)
                                    .addComponent(fieldPasData, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)))
                            .addGroup(paneCadastroPassagemLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btCancelPas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSalvarPassagem)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        paneCadastroPassagemLayout.setVerticalGroup(
            paneCadastroPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCadastroPassagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneCadastroPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fieldPasData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneCadastroPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fieldPasOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneCadastroPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fieldPasDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneCadastroPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fieldPasPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCadastroPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(fieldPasQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(paneCadastroPassagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvarPassagem)
                    .addComponent(btCancelPas))
                .addGap(36, 36, 36))
        );

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Edição de Passagem");

        jLabel14.setText("Data");

        jLabel15.setText("Origem");

        jLabel16.setText("Destino");

        jLabel17.setText("Preço");

        jLabel18.setText("Quantidade");

        fieldPasDataEdit.setText("DD/MM/YYYY");
        fieldPasDataEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPasDataEditActionPerformed(evt);
            }
        });

        fieldPasOrigemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPasOrigemEditActionPerformed(evt);
            }
        });

        btCancelEditPas.setText("Cancelar");
        btCancelEditPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelEditPasActionPerformed(evt);
            }
        });

        btSalvarEditPassagem.setText("Salvar");
        btSalvarEditPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarEditPassagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneCadastroPassagemEditLayout = new javax.swing.GroupLayout(paneCadastroPassagemEdit);
        paneCadastroPassagemEdit.setLayout(paneCadastroPassagemEditLayout);
        paneCadastroPassagemEditLayout.setHorizontalGroup(
            paneCadastroPassagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCadastroPassagemEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(paneCadastroPassagemEditLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(paneCadastroPassagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneCadastroPassagemEditLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(220, 220, 220))
                    .addGroup(paneCadastroPassagemEditLayout.createSequentialGroup()
                        .addGroup(paneCadastroPassagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paneCadastroPassagemEditLayout.createSequentialGroup()
                                .addGroup(paneCadastroPassagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(paneCadastroPassagemEditLayout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneCadastroPassagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldPasOrigemEdit)
                                    .addComponent(fieldPasDestinoEdit)
                                    .addComponent(fieldPasQuantidadeEdit)
                                    .addComponent(fieldPasPrecoEdit)
                                    .addComponent(fieldPasDataEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)))
                            .addGroup(paneCadastroPassagemEditLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btCancelEditPas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSalvarEditPassagem)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        paneCadastroPassagemEditLayout.setVerticalGroup(
            paneCadastroPassagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCadastroPassagemEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneCadastroPassagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(fieldPasDataEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneCadastroPassagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(fieldPasOrigemEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneCadastroPassagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(fieldPasDestinoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneCadastroPassagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(fieldPasPrecoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCadastroPassagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(fieldPasQuantidadeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(paneCadastroPassagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvarEditPassagem)
                    .addComponent(btCancelEditPas))
                .addGap(36, 36, 36))
        );

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Edição de Hospedagem");

        jLabel20.setText("Hotel");

        jLabel21.setText("Cidade");

        jLabel22.setText("Preço");

        jLabel23.setText("Quantidade");

        fieldHospHotelEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHospHotelEditActionPerformed(evt);
            }
        });

        fieldHospCidadeEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHospCidadeEditActionPerformed(evt);
            }
        });

        btHospCancelaEdit.setText("Cancelar");
        btHospCancelaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHospCancelaEditActionPerformed(evt);
            }
        });

        btHospSalvaEdit.setText("Salvar");
        btHospSalvaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHospSalvaEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneCadastroHospedagemEditLayout = new javax.swing.GroupLayout(paneCadastroHospedagemEdit);
        paneCadastroHospedagemEdit.setLayout(paneCadastroHospedagemEditLayout);
        paneCadastroHospedagemEditLayout.setHorizontalGroup(
            paneCadastroHospedagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCadastroHospedagemEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(paneCadastroHospedagemEditLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(paneCadastroHospedagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneCadastroHospedagemEditLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(220, 220, 220))
                    .addGroup(paneCadastroHospedagemEditLayout.createSequentialGroup()
                        .addGroup(paneCadastroHospedagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paneCadastroHospedagemEditLayout.createSequentialGroup()
                                .addGroup(paneCadastroHospedagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(paneCadastroHospedagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldHospCidadeEdit, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fieldHospPrecoEdit, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fieldHospQuantidadeEdit)
                                    .addComponent(fieldHospHotelEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)))
                            .addGroup(paneCadastroHospedagemEditLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btHospCancelaEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btHospSalvaEdit)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        paneCadastroHospedagemEditLayout.setVerticalGroup(
            paneCadastroHospedagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCadastroHospedagemEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneCadastroHospedagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(fieldHospHotelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneCadastroHospedagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(fieldHospCidadeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneCadastroHospedagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(fieldHospPrecoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneCadastroHospedagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(fieldHospQuantidadeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(paneCadastroHospedagemEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHospSalvaEdit)
                    .addComponent(btHospCancelaEdit))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(introPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(94, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(paneCadastroHospedagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paneCadastroPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paneCadastroPassagemEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paneCadastroHospedagemEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(85, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(introPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1426, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneCadastroHospedagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneCadastroHospedagemEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneCadastroPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneCadastroPassagemEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldHospHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHospHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHospHotelActionPerformed

    private void btAddPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddPasActionPerformed
        // TODO add your handling code here:
        controller.abrirPaneCadastroPassagem();
    }//GEN-LAST:event_btAddPasActionPerformed

    private void fieldHospCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHospCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHospCidadeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        controller.fecharCadastroHospedagem();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fieldPasDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPasDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPasDataActionPerformed

    private void fieldPasOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPasOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPasOrigemActionPerformed

    private void btCancelPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelPasActionPerformed
        // TODO add your handling code here:
        controller.fecharCadastroPassagens();
    }//GEN-LAST:event_btCancelPasActionPerformed

    private void btAddHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddHospActionPerformed
        // TODO add your handling code here:
        controller.abrirPaneCadastroHospedagem();
    }//GEN-LAST:event_btAddHospActionPerformed

    private void btSalvarPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarPassagemActionPerformed
        // TODO add your handling code here:
        controller.addPassagem();
    }//GEN-LAST:event_btSalvarPassagemActionPerformed

    private void fieldPasDataEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPasDataEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPasDataEditActionPerformed

    private void fieldPasOrigemEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPasOrigemEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPasOrigemEditActionPerformed

    private void btCancelEditPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelEditPasActionPerformed
        // TODO add your handling code here:
        controller.cancelaEditPassagem();
    }//GEN-LAST:event_btCancelEditPasActionPerformed

    private void btSalvarEditPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarEditPassagemActionPerformed
        try {
            // TODO add your handling code here:
            controller.confirmaEditPassagem();
        } catch (RemoteException ex) {
            Logger.getLogger(dollynhoAirlinesJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSalvarEditPassagemActionPerformed

    private void editPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPasActionPerformed
        // TODO add your handling code here:
        controller.abreEditPassagem();
    }//GEN-LAST:event_editPasActionPerformed

    private void btRemovePasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemovePasActionPerformed
        // TODO add your handling code here:
        controller.removePassagem();
    }//GEN-LAST:event_btRemovePasActionPerformed

    private void btEditHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditHospActionPerformed
        // TODO add your handling code here:
        controller.abreEditHospedagem();
    }//GEN-LAST:event_btEditHospActionPerformed

    private void fieldHospHotelEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHospHotelEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHospHotelEditActionPerformed

    private void fieldHospCidadeEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHospCidadeEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHospCidadeEditActionPerformed

    private void btHospCancelaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHospCancelaEditActionPerformed
        // TODO add your handling code here:
        controller.cancelaEditHospedagem();
    }//GEN-LAST:event_btHospCancelaEditActionPerformed

    private void btHospSalvaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHospSalvaEditActionPerformed
        try {
            // TODO add your handling code here:
            controller.confirmaEditHospedagem();
        } catch (RemoteException ex) {
            Logger.getLogger(dollynhoAirlinesJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btHospSalvaEditActionPerformed

    private void btRemoveHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveHospActionPerformed
        // TODO add your handling code here:
        controller.removeHospedagem();
    }//GEN-LAST:event_btRemoveHospActionPerformed
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dollynhoAirlinesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dollynhoAirlinesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dollynhoAirlinesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dollynhoAirlinesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
               
        
        
        System.out.println("Iniciado server RMI");
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new dollynhoAirlinesJFrame().setVisible(true);
                } catch (RemoteException ex) {
                    Logger.getLogger(dollynhoAirlinesJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (AlreadyBoundException ex) {
                    Logger.getLogger(dollynhoAirlinesJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(dollynhoAirlinesJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(dollynhoAirlinesJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(dollynhoAirlinesJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(dollynhoAirlinesJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public JTextField getFieldHospCidade() {
        return fieldHospCidade;
    }

    public JTextField getFieldHospHotel() {
        return fieldHospHotel;
    }

    public JTextField getFieldHospPreco() {
        return fieldHospPreco;
    }

    public JTextField getFieldHospQuantidade() {
        return fieldHospQuantidade;
    }

    public JTextField getFieldPasData() {
        return fieldPasData;
    }

    public JTextField getFieldPasDestino() {
        return fieldPasDestino;
    }

    public JTextField getFieldPasOrigem() {
        return fieldPasOrigem;
    }

    public JTextField getFieldPasPreco() {
        return fieldPasPreco;
    }

    public JTextField getFieldPasQuantidade() {
        return fieldPasQuantidade;
    }

    public JPanel getIntroPane() {
        return introPane;
    }

    public JPanel getPaneCadastroHospedagem() {
        return paneCadastroHospedagem;
    }

    public JPanel getPaneCadastroPassagem() {
        return paneCadastroPassagem;
    }

    public JTable getTabelaHospedagem() {
        return tabelaHospedagem;
    }

    public JTable getTabelaNotificacoes() {
        return tabelaNotificacoes;
    }

    public JTable getTabelaPassagens() {
        return tabelaPassagens;
    }

    public JTextField getFieldPasDataEdit() {
        return fieldPasDataEdit;
    }

    public JTextField getFieldPasDestinoEdit() {
        return fieldPasDestinoEdit;
    }

    public JTextField getFieldPasOrigemEdit() {
        return fieldPasOrigemEdit;
    }

    public JTextField getFieldPasPrecoEdit() {
        return fieldPasPrecoEdit;
    }

    public JTextField getFieldPasQuantidadeEdit() {
        return fieldPasQuantidadeEdit;
    }

    public JPanel getPaneCadastroPassagemEdit() {
        return paneCadastroPassagemEdit;
    }

    public JPanel getPaneCadastroHospedagemEdit() {
        return paneCadastroHospedagemEdit;
    }

    public JTextField getFieldHospCidadeEdit() {
        return fieldHospCidadeEdit;
    }

    public JTextField getFieldHospHotelEdit() {
        return fieldHospHotelEdit;
    }

    public JTextField getFieldHospPrecoEdit() {
        return fieldHospPrecoEdit;
    }

    public JTextField getFieldHospQuantidadeEdit() {
        return fieldHospQuantidadeEdit;
    }

    
   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddHosp;
    private javax.swing.JButton btAddPas;
    private javax.swing.JButton btCancelEditPas;
    private javax.swing.JButton btCancelPas;
    private javax.swing.JButton btEditHosp;
    private javax.swing.JButton btHospCancelaEdit;
    private javax.swing.JButton btHospSalvaEdit;
    private javax.swing.JButton btRemoveHosp;
    private javax.swing.JButton btRemovePas;
    private javax.swing.JButton btSalvarEditPassagem;
    private javax.swing.JButton btSalvarPassagem;
    private javax.swing.JButton editPas;
    private javax.swing.JTextField fieldHospCidade;
    private javax.swing.JTextField fieldHospCidadeEdit;
    private javax.swing.JTextField fieldHospHotel;
    private javax.swing.JTextField fieldHospHotelEdit;
    private javax.swing.JTextField fieldHospPreco;
    private javax.swing.JTextField fieldHospPrecoEdit;
    private javax.swing.JTextField fieldHospQuantidade;
    private javax.swing.JTextField fieldHospQuantidadeEdit;
    private javax.swing.JTextField fieldPasData;
    private javax.swing.JTextField fieldPasDataEdit;
    private javax.swing.JTextField fieldPasDestino;
    private javax.swing.JTextField fieldPasDestinoEdit;
    private javax.swing.JTextField fieldPasOrigem;
    private javax.swing.JTextField fieldPasOrigemEdit;
    private javax.swing.JTextField fieldPasPreco;
    private javax.swing.JTextField fieldPasPrecoEdit;
    private javax.swing.JTextField fieldPasQuantidade;
    private javax.swing.JTextField fieldPasQuantidadeEdit;
    private javax.swing.JPanel introPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel paneCadastroHospedagem;
    private javax.swing.JPanel paneCadastroHospedagemEdit;
    private javax.swing.JPanel paneCadastroPassagem;
    private javax.swing.JPanel paneCadastroPassagemEdit;
    private javax.swing.JTable tabelaHospedagem;
    private javax.swing.JTable tabelaNotificacoes;
    private javax.swing.JTable tabelaPassagens;
    // End of variables declaration//GEN-END:variables
}
